package co.com.project.certification.examples.models;

import lombok.Data;

@Data
public class Example {
    //The get and set methods of the variables are automatically generated by the lombok library or can be created manually.
    private String name;
    private String last_name;
    private long phone;
}
